Repository NeuronActivation/kalja-xyz, pull requests merged in 2025-02, with the labels that each got.

#59 Rerolled card restores after refresh
  src/lib/components/Game.svelte
Labels: bug

#61 Replay starts the very same game
  src/lib/components/End.svelte
  src/lib/stores/gameStore.ts
Labels: bug

#62 TSDoc + refactoring
  src/lib/components/Header.svelte
  src/lib/components/Lobby.svelte
  src/lib/constants/applicationState.ts
  src/lib/constants/isBrowser.ts
  src/lib/interfaces/card.ts
  src/lib/interfaces/gameEvent.ts
  src/lib/interfaces/gameState.ts
  src/lib/interfaces/metadata.ts
  src/lib/interfaces/player.ts
  src/lib/languages/language.ts
  src/lib/languages/load.ts
  src/lib/managers/game.ts
  src/lib/stores/gameStore.ts
  src/lib/stores/languageStore.ts
  src/lib/utils/seed.ts
  src/lib/utils/storage.ts
  src/routes/+layout.ts
Labels: documentation, refactor

#54 Add LICENSE
  LICENSE
Labels: documentation

#46 Initial progressive web application (PWA) implementation
  src/app.html
  src/service-worker/index.ts
  static/favicon.png
  static/icons/icon-192x192.png
  static/icons/icon-512x512.png
  static/icons/maskable-192x192.png
  static/manifest.json
  static/screenshots/desktop.png
  static/screenshots/mobile.png
Labels: enhancement

#66 Add card-suggestion issue template
  .github/ISSUE_TEMPLATE/card-suggestion.yml
Labels: documentation

#64 Tag system
  src/lib/components/Lobby.svelte
  src/lib/constants/tag.ts
  src/lib/interfaces/card.ts
  src/lib/interfaces/gameState.ts
  src/lib/languages/load.ts
  src/lib/stores/gameStore.ts
  static/cards/english.json
  static/cards/finnish.json
  static/locales/english.json
  static/locales/finnish.json
Labels: enhancement

#72 Improve responsiveness
  src/lib/components/Game.svelte
  src/lib/components/Header.svelte
Labels: bug

#67 Modify README.md
  .github/README.md
  .github/images/gameplay.png
  .github/images/lobby.png
  .github/images/start.png
Labels: documentation

#74 Close settings menu by default
  src/lib/components/Lobby.svelte
Labels: bug

#75 Added 16 new cards
  static/cards/english.json
  static/cards/finnish.json
Labels: card-suggestion

#76 Nested language structure for cards
  src/lib/interfaces/card.ts
  src/lib/interfaces/gameState.ts
  src/lib/languages/language.ts
  src/lib/languages/load.ts
  src/lib/stores/languageStore.ts
  static/cards/cards.json
  static/cards/english.json
  static/cards/finnish.json
Labels: enhancement

#77 Fixing typos in comments
  src/lib/components/Game.svelte
  src/lib/components/Lobby.svelte
  src/lib/interfaces/card.ts
  src/lib/interfaces/gameState.ts
  src/lib/languages/load.ts
  src/lib/managers/game.ts
Labels: documentation

#80 Remove "targetPlayer" and "timedEvent" from "cards.json"
  src/lib/languages/load.ts
  static/cards/cards.json
Labels: refactor

#84 Deno migration
  .envrc
  .github/README.md
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .prettierignore
  .prettierrc
  deno.json
  deno.lock
  flake.lock
  flake.nix
  package.json
  pnpm-lock.yaml
  src/app.html
  src/lib/components/Game.svelte
  src/lib/constants/applicationState.ts
  src/lib/constants/tag.ts
  src/lib/interfaces/gameState.ts
  src/lib/languages/language.ts
  src/lib/languages/load.ts
  src/lib/managers/game.ts
  src/lib/stores/gameStore.ts
  src/lib/stores/languageStore.ts
  src/service-worker/index.ts
  svelte.config.js
Labels: enhancement, dependencies

#85 Update file structure
  src/lib/cards/cardStorage.ts
  src/lib/cards/cardUtils.ts
  src/lib/cards/createCards.ts
  src/lib/components/Game.svelte
  src/lib/components/Header.svelte
  src/lib/constants/language.ts
  src/lib/gameState/createNewGame.ts
  src/lib/gameState/gameStateStorage.ts
  src/lib/i18n/index.ts
  src/lib/i18n/localeStorage.ts
  src/lib/interfaces/gameState.ts
  src/lib/interfaces/languageData.ts
  src/lib/languages/load.ts
  src/lib/stores/gameStore.ts
  src/lib/stores/languageData.ts
  src/lib/stores/languageStore.ts
  src/lib/utils/seed.ts
  src/lib/utils/storage.ts
  src/lib/utils/targetStorage.ts
  src/routes/+layout.ts
Labels: refactor
